CANONICAL_HOMEOWNER_TASKS = [
    {"category": "plumbing", "query": "replace toilet", "priority": 1},
    {"category": "plumbing", "query": "repair running toilet", "priority": 1},
    {"category": "plumbing", "query": "replace toilet fill valve", "priority": 1},
    {"category": "plumbing", "query": "replace toilet flapper", "priority": 1},
    {"category": "plumbing", "query": "unclog toilet", "priority": 1},
    {"category": "plumbing", "query": "replace kitchen faucet", "priority": 1},
    {"category": "plumbing", "query": "replace bathroom faucet", "priority": 1},
    {"category": "plumbing", "query": "repair leaky faucet", "priority": 1},
    {"category": "plumbing", "query": "replace sink drain assembly", "priority": 1},
    {"category": "plumbing", "query": "replace sink disposal", "priority": 1},
    {"category": "plumbing", "query": "unclog sink drain", "priority": 1},
    {"category": "plumbing", "query": "replace shower cartridge", "priority": 1},
    {"category": "plumbing", "query": "install shower head", "priority": 2},
    {"category": "plumbing", "query": "replace shutoff valve", "priority": 2},
    {"category": "plumbing", "query": "install dishwasher water line", "priority": 2},
    {"category": "plumbing", "query": "replace sump pump", "priority": 2},
    {"category": "plumbing", "query": "install water softener", "priority": 2},
    {"category": "plumbing", "query": "replace water heater", "priority": 2},
    {"category": "electrical", "query": "replace light switch", "priority": 1},
    {"category": "electrical", "query": "replace electrical outlet", "priority": 1},
    {"category": "electrical", "query": "install gfci outlet", "priority": 1},
    {"category": "electrical", "query": "install dimmer switch", "priority": 1},
    {"category": "electrical", "query": "replace ceiling light fixture", "priority": 1},
    {"category": "electrical", "query": "install ceiling fan", "priority": 1},
    {"category": "electrical", "query": "replace smoke detector", "priority": 1},
    {"category": "electrical", "query": "install smart thermostat", "priority": 1},
    {"category": "electrical", "query": "install smart switch", "priority": 2},
    {"category": "electrical", "query": "add electrical outlet", "priority": 2},
    {"category": "electrical", "query": "replace doorbell transformer", "priority": 2},
    {"category": "electrical", "query": "install exterior light", "priority": 2},
    {"category": "hvac", "query": "replace furnace filter", "priority": 1},
    {"category": "hvac", "query": "clean dryer vent", "priority": 1},
    {"category": "hvac", "query": "install bathroom exhaust fan", "priority": 1},
    {"category": "hvac", "query": "replace thermostat", "priority": 1},
    {"category": "hvac", "query": "clean ac condenser coils", "priority": 2},
    {"category": "hvac", "query": "seal duct leak", "priority": 2},
    {"category": "appliances", "query": "install dishwasher", "priority": 1},
    {"category": "appliances", "query": "replace dishwasher", "priority": 1},
    {"category": "appliances", "query": "install over range microwave", "priority": 1},
    {"category": "appliances", "query": "replace refrigerator water filter", "priority": 1},
    {"category": "appliances", "query": "install washing machine", "priority": 1},
    {"category": "appliances", "query": "replace dryer belt", "priority": 2},
    {"category": "appliances", "query": "install range hood", "priority": 2},
    {"category": "doors_windows", "query": "replace interior door", "priority": 1},
    {"category": "doors_windows", "query": "adjust sagging door", "priority": 1},
    {"category": "doors_windows", "query": "install door knob", "priority": 1},
    {"category": "doors_windows", "query": "install deadbolt", "priority": 1},
    {"category": "doors_windows", "query": "replace weatherstripping", "priority": 1},
    {"category": "doors_windows", "query": "replace window screen", "priority": 1},
    {"category": "doors_windows", "query": "replace window sash rope", "priority": 2},
    {"category": "doors_windows", "query": "install storm door", "priority": 2},
    {"category": "drywall_paint", "query": "patch drywall hole", "priority": 1},
    {"category": "drywall_paint", "query": "repair drywall crack", "priority": 1},
    {"category": "drywall_paint", "query": "tape and mud drywall", "priority": 1},
    {"category": "drywall_paint", "query": "paint interior wall", "priority": 1},
    {"category": "drywall_paint", "query": "paint ceiling", "priority": 1},
    {"category": "drywall_paint", "query": "caulk baseboards", "priority": 1},
    {"category": "drywall_paint", "query": "remove popcorn ceiling", "priority": 2},
    {"category": "flooring_tile", "query": "install vinyl plank flooring", "priority": 1},
    {"category": "flooring_tile", "query": "install laminate flooring", "priority": 1},
    {"category": "flooring_tile", "query": "repair squeaky floor", "priority": 2},
    {"category": "flooring_tile", "query": "replace cracked tile", "priority": 1},
    {"category": "flooring_tile", "query": "grout tile", "priority": 1},
    {"category": "flooring_tile", "query": "recaulk bathtub", "priority": 1},
    {"category": "flooring_tile", "query": "tile shower floor", "priority": 2},
    {"category": "flooring_tile", "query": "install tile backsplash", "priority": 1},
    {"category": "carpentry", "query": "frame a wall", "priority": 2},
    {"category": "carpentry", "query": "install baseboard trim", "priority": 1},
    {"category": "carpentry", "query": "install crown molding", "priority": 2},
    {"category": "carpentry", "query": "build closet shelves", "priority": 1},
    {"category": "carpentry", "query": "repair stair tread", "priority": 2},
    {"category": "carpentry", "query": "install handrail", "priority": 1},
    {"category": "exterior", "query": "repair deck board", "priority": 1},
    {"category": "exterior", "query": "stain deck", "priority": 1},
    {"category": "exterior", "query": "pour concrete slab", "priority": 2},
    {"category": "exterior", "query": "set fence post in concrete", "priority": 1},
    {"category": "exterior", "query": "install mailbox post", "priority": 1},
    {"category": "exterior", "query": "repair vinyl siding", "priority": 1},
    {"category": "exterior", "query": "install house wrap", "priority": 2},
    {"category": "roofing_gutters", "query": "clean gutters", "priority": 1},
    {"category": "roofing_gutters", "query": "repair gutter leak", "priority": 1},
    {"category": "roofing_gutters", "query": "install gutter guards", "priority": 2},
    {"category": "roofing_gutters", "query": "replace asphalt shingle", "priority": 1},
    {"category": "roofing_gutters", "query": "repair roof flashing", "priority": 2},
    {"category": "insulation_energy", "query": "install attic insulation", "priority": 1},
    {"category": "insulation_energy", "query": "air seal attic", "priority": 2},
    {"category": "insulation_energy", "query": "weatherstrip exterior door", "priority": 1},
    {"category": "insulation_energy", "query": "install window insulation film", "priority": 2},
    {"category": "safety_maintenance", "query": "test sump pump", "priority": 1},
    {"category": "safety_maintenance", "query": "shut off main water valve", "priority": 1},
    {"category": "safety_maintenance", "query": "locate circuit breaker", "priority": 1},
    {"category": "safety_maintenance", "query": "reset gfci outlet", "priority": 1},
    {"category": "safety_maintenance", "query": "clean weep holes", "priority": 2},
    {"category": "safety_maintenance", "query": "replace furnace humidifier pad", "priority": 2},
    {"category": "landscape_drainage", "query": "install french drain", "priority": 2},
    {"category": "landscape_drainage", "query": "repair sprinkler head", "priority": 1},
    {"category": "landscape_drainage", "query": "install hose bib vacuum breaker", "priority": 2},
    {"category": "landscape_drainage", "query": "seal driveway cracks", "priority": 1},
    {"category": "landscape_drainage", "query": "pressure wash siding", "priority": 1},
    {"category": "landscape_drainage", "query": "install landscape edging", "priority": 2},
]


def taxonomy_summary() -> dict:
    counts = {}
    for item in CANONICAL_HOMEOWNER_TASKS:
        counts[item["category"]] = counts.get(item["category"], 0) + 1
    return {
        "task_count": len(CANONICAL_HOMEOWNER_TASKS),
        "categories": counts,
    }
